### ISSUE TITLE
formatter doesn't work

### ISSUE THREAD

**Issue by xiangnanscu** [idahogurl/vs-code-prettier-eslint#164]
**Describe the bug**
formtter doesn't work

**To Reproduce**
just select all and choose `Format Document` and nothing happens

**Expected behavior**
work

**Example Project**

**Screenshots**

**Versions (please complete the following information):**
- VS Code Prettier ESLint extension [e.g. 3.1.0]
- Visual Studio Code: 1.78.0
- Node: 18.12.1
- Package Manager npm 9.6.0
- prettier: 2.7.1
- eslint: 8.22.0

**System Specifications (please complete the following information):**
- OS: wsl2 ubuntu 20.04
- Processor: [e.g. Intel i7 6-core 2.6Ghz]
- RAM Size: [e.g. 16 GB]
 
**Additional context**

**Comment by xiangnanscu** [comment]
I'm sure I set `rvest.vs-code-prettier-eslint` as formatter in my `.vscode/setting.json`:
```JSON5
  "editor.formatOnPaste": false, // required
  "editor.formatOnType": false, // required
  "editor.formatOnSave": true, // optional
  "editor.formatOnSaveMode": "file", // required to format on save
  "files.autoSave": "onFocusChange", // optional but recommended
  "vs-code-prettier-eslint.prettierLast": false,
```

**Comment by CSFlorin** [comment]
Same here. I'm getting:

```
Error: Failed to load plugin 'jsx-a11y' declared in 'CLIOptions': The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received '' 
TypeError: Failed to load plugin 'jsx-a11y' declared in 'CLIOptions': The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received ''
	at new NodeError (node:internal/errors:387:5)
	at createRequire (node:internal/modules/cjs/loader:1304:13)
	at Object.resolve (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2325:16)
	at ModuleResolver.resolve (/Users/f/starter/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js:210:48)
	at ConfigArrayFactory._loadPlugin (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3392:33)
	at ConfigArrayFactory._loadPlugin (/Users/f/starter/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js:219:43)
	at /Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3283:33
	at Array.reduce (<anonymous>)
	at ConfigArrayFactory._loadPlugins (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3279:22)
	at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3079:44)
	at _normalizeObjectConfigDataBody.next (<anonymous>)
	at ConfigArrayFactory._normalizeObjectConfigData (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3019:20)
	at _normalizeObjectConfigData.next (<anonymous>)
	at ConfigArrayFactory.create (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2814:16)
	at createCLIConfigArray (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3624:47)
	at CascadingConfigArrayFactory.clearCache (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3795:32)
	at new ESLint (/Users/f/starter/node_modules/eslint/lib/eslint/eslint.js:449:32)
	at $me (/Users/f/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js:185:69)
	at /Users/f/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js:193:700
	at zme (/Users/f/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js:185:1458)
Error: Failed to load plugin 'jsx-a11y' declared in 'CLIOptions': The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received '' 
TypeError: Failed to load plugin 'jsx-a11y' declared in 'CLIOptions': The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received ''
	at new NodeError (node:internal/errors:387:5)
	at createRequire (node:internal/modules/cjs/loader:1304:13)
	at Object.resolve (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2325:16)
	at ModuleResolver.resolve (/Users/f/starter/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js:210:48)
	at ConfigArrayFactory._loadPlugin (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3392:33)
	at ConfigArrayFactory._loadPlugin (/Users/f/starter/node_modules/@rushstack/eslint-patch/lib/modern-module-resolution.js:219:43)
	at /Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3283:33
	at Array.reduce (<anonymous>)
	at ConfigArrayFactory._loadPlugins (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3279:22)
	at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3079:44)
	at _normalizeObjectConfigDataBody.next (<anonymous>)
	at ConfigArrayFactory._normalizeObjectConfigData (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3019:20)
	at _normalizeObjectConfigData.next (<anonymous>)
	at ConfigArrayFactory.create (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2814:16)
	at createCLIConfigArray (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3624:47)
	at CascadingConfigArrayFactory.clearCache (/Users/f/starter/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3795:32)
	at new ESLint (/Users/f/starter/node_modules/eslint/lib/eslint/eslint.js:449:32)
	at $me (/Users/f/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js:185:69)
	at /Users/f/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js:193:700
	at zme (/Users/f/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js:185:1458)
```

I see a similar issue here https://github.com/idahogurl/vs-code-prettier-eslint/issues/159 Looks like a mess to fix it

**Comment by idahogurl** [comment]
@xiangnanscu May I close this issue since there is a workaround and the source of the issue is the `@rushstack/eslint-patch`

**Comment by xiangnanscu** [comment]
yes please

**Comment by xiangnanscu** [comment]
workaround: https://github.com/idahogurl/vs-code-prettier-eslint/issues/72#issuecomment-1247516987
