### ISSUE TITLE
格式化时报错

### ISSUE THREAD

**Issue by NT-Sasoli** [idahogurl/vs-code-prettier-eslint#179]
Error: Expected `input` to be a `string`, got `object` 
TypeError: Expected `input` to be a `string`, got `object`
    at fb.exports (/Users/sasoli/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js:7:7296)
    at /Users/sasoli/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js:192:25
    at zme (/Users/sasoli/.vscode/extensions/rvest.vs-code-prettier-eslint-5.1.0/dist/extension.js:185:1460)

**Comment by NT-Sasoli** [comment]
当我将 prettier eslint eslint-plugin-prettier vue-eslint-parser 全部版本降级后，格式化成功了，但非常希望能适配新的版本
