### ISSUE TITLE
Don't support ESlint v9.x

### ISSUE THREAD

**Issue by NekoLemon** [idahogurl/vs-code-prettier-eslint#236]
log as below:

```
Error: Could not warm up worker. Formatting a file for the first time may take longer than usual.
Message: Invalid Options:
- Unknown options: ignorePath, resolvePluginsRelativeTo, rulePaths, useEslintrc
- 'resolvePluginsRelativeTo' has been removed.
- 'ignorePath' has been removed.
- 'rulePaths' has been removed. Please define your rules using plugins.
Stacktrace: Error: Invalid Options:
- Unknown options: ignorePath, resolvePluginsRelativeTo, rulePaths, useEslintrc
- 'resolvePluginsRelativeTo' has been removed.
- 'ignorePath' has been removed.
- 'rulePaths' has been removed. Please define your rules using plugins.
    at processOptions (e:\eslint-test\node_modules\eslint\lib\eslint\eslint-helpers.js:853:15)
    at new ESLint (e:\eslint-test\node_modules\eslint\lib\eslint\eslint.js:688:34)
    at getESLint (e:\eslint-test\node_modules\prettier-eslint\dist\utils.js:337:12)
    at getESLintConfig (e:\eslint-test\node_modules\prettier-eslint\dist\index.js:268:39)
    at analyze (e:\eslint-test\node_modules\prettier-eslint\dist\index.js:80:77)
    at format (e:\eslint-test\node_modules\prettier-eslint\dist\index.js:50:13)
```

**Comment by Sayrix** [comment]
Bump?

**Comment by R1D3R175** [comment]
+1

**Comment by prochor666** [comment]
+1

**Comment by JarzaCode** [comment]
+1

**Comment by LegitTrevorTiernan** [comment]
For those still having issues it might be worth looking into 
https://github.com/idahogurl/vs-code-prettier-eslint/issues/222

**Comment by Sayrix** [comment]
😡

**Comment by space7panda** [comment]
same

**Comment by Laffery** [comment]
any progress?

**Comment by addemod** [comment]
+1

**Comment by mcelligottnick** [comment]
+1

**Comment by mihajanstrehovec** [comment]
+1

**Comment by Mettbrot** [comment]
@idahogurl Is this repo still maintained? If not would you care to set it to archived so that people can move on? Thanks.

**Comment by idahogurl** [comment]
@Mettbrot This extension uses the `prettier-eslint` package which has not been updated to support ESLint 9. Until the `prettier-eslint` package is updated, this extension will continue to use ESLint 8. As you can see, there was a PR created to support ESLint but it was closed due to inactivity. https://github.com/prettier/prettier-eslint/pull/1036

**Comment by phun-ky** [comment]
@idahogurl yep, I started an attempt to convert `pretter-eslint` to support ESLint@9, but having issues with the tests. I'm not an OG contributor or maintainer of this, so it goes very slowly. 

I think the only thing that remains is to get _all_ the tests to run/or have other viable tests, and do a sanity check to see if it works as intended. Still waiting for the question about config presedence.

Feel free to aid me or the maintainers in this: https://github.com/prettier/prettier-eslint/pull/1036

**Comment by R1D3R175** [comment]
In case anyone is bumping into this, you can still use Prettier in ESLint with `eslint-plugin-prettier` and configure Prettier in `prettier.config.js`. There is some difference between `prettier-eslint` and `eslint-plugin-prettier` as the latter runs Prettier as a rule while `prettier-eslint` runs Prettier *before* running ESLint, thus allowing the Prettier output to not comply with your ESLint linting rules; still, if you are ok with running Prettier as an ESLint rule, this will work for you.

This is how my Angular environment is setup
```javascript
// eslint.config.js
// @ts-check
const eslint = require("@eslint/js");
const tseslint = require("typescript-eslint");
const angular = require("angular-eslint");
const prettierRecommended = require("eslint-plugin-prettier/recommended");

module.exports = tseslint.config(
  {
    files: ["src/**/*.ts"],
    extends: [
      eslint.configs.recommended,
      ...tseslint.configs.recommended,
      ...tseslint.configs.stylistic,
      ...angular.configs.tsRecommended,
      prettierRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      "@angular-eslint/directive-selector": [
        "error",
        {
          type: "attribute",
          prefix: "app",
          style: "camelCase",
        },
      ],
      "@angular-eslint/component-selector": [
        "error",
        {
          type: "element",
          prefix: "app",
          style: "kebab-case",
        },
      ],
    },
  },
  {
    files: ["**/*.html"],
    extends: [
      ...angular.configs.templateRecommended,
      ...angular.configs.templateAccessibility,
    ],
    rules: {},
  }
);

```
```javascript
// prettier.config.js
module.exports = require('prettier-config-xo/space');
```

**Comment by Sayrix** [comment]
> This issue is stale because it has been open for 14 days with no activity.

no

**Comment by naedx** [comment]
+1

**Comment by JounQin** [comment]
Please help to test out the first prototype https://github.com/prettier/prettier-eslint/releases/tag/v17.0.0-alpha.1 which only supports Flat Config yet, legacy eslintrc support will be added back soon later.

**Comment by Mettbrot** [comment]
Thank you!! @idahogurl could you maybe also release an alpha version of the Plugin for us to test?

**Comment by Mettbrot** [comment]
ping @idahogurl

**Comment by ifsmile** [comment]
+1

**Comment by Mettbrot** [comment]
Rebecca, this Addon has 3,5 Million installs. If you could send a life sign that this plugin is still being worked on, that would be great!

**Comment by BinToss** [comment]
> Rebecca, this Addon has 3,5 Million installs. If you could send a life sign that this plugin is still being worked on, that would be great!

@Mettbrot this extension relies on the project "prettier-eslint". JounQin  contributed ESLint v9 Flat config support and it was released with https://github.com/prettier/prettier-eslint/releases/tag/v17.0.0-alpha.0.

Idahogurl is probably waiting for a full release. However, you could contribute toward a prerelease of this extension by updating and refactoring for the prettier-eslint v17 prerelease.

**Comment by BinToss** [comment]
> Please help to test out the first prototype https://github.com/prettier/prettier-eslint/releases/tag/v17.0.0-alpha.1 which only supports Flat Config yet, legacy eslintrc support will be added back soon later.

@JounQin have you considered using `@eslint/eslintrc` for legacy config compatibility?

**Comment by JounQin** [comment]
As you quoted:

> which only supports Flat Config yet, legacy eslintrc support will be added back soon later.

**Comment by Shotplay** [comment]
> This issue is stale because it has been open for 14 days with no activity.

no

**Comment by lfpei** [comment]
什么时候支持eslint9

**Comment by Sayrix** [comment]
> 什么时候支持eslint9

When the [`prettier-eslint`](https://github.com/prettier/prettier-eslint) package will support eslint 9

**Comment by aminomancer** [comment]
All you have to do is update prettier-eslint to `17.0.0-alpha.1` in package.json and it works. Go to `~\.vscode\extensions\rvest.vs-code-prettier-eslint-6.0.0` and edit it yourself for now.

**Comment by Sayrix** [comment]
no

**Comment by aidasbui** [comment]
**Workaround** for people using VSCode with `eslint` v9 + `prettier` v3 is to ditch this extension and use extensions `esbenp.prettier-vscode` and `dbaeumer.vscode-eslint`. 

1. Set `esbenp.prettier-vscode` as your default formatter and tick the "Format on save" checkbox in VSCode's settings. It will recognize your `.prettierrc` config and do its thing.
2. For your `eslint.config.js` - change your VSCode user's `settings.json` and add:
```json
"editor.codeActionsOnSave": {
    "source.fixAll": "explicit"
  }
```

This formats with prettier and runs `eslint --fix` for me on save, although I'm not sure of precedence. 

My linting/formatting related package versions:
```json
    "@eslint/js": "^9.33.0",
    "@tanstack/eslint-plugin-query": "^5.83.1",
    "@typescript-eslint/eslint-plugin": "^8.40.0",
    "@typescript-eslint/parser": "^8.40.0",
    "eslint": "^9.33.0",
    "eslint-plugin-perfectionist": "^4.15.0",
    "eslint-plugin-react-hooks": "^5.2.0",
    "eslint-plugin-react-refresh": "^0.4.20",
    "prettier": "^3.6.2",
    "prettier-plugin-tailwindcss": "^0.6.14",
    "typescript": "^5.9.2",
    "typescript-eslint": "^8.40.0"
```

**Comment by Mettbrot** [comment]
I started a new move, maybe we can finally get this released... https://github.com/prettier/prettier-eslint/issues/1199

**Comment by seanCodes** [comment]
@aminomancer's solution worked for me :pray:

> All you have to do is update prettier-eslint to 17.0.0-alpha.1 in package.json and it works.

**Comment by BinToss** [comment]
Just because it's stale doesn't mean it's not an issue.

**Comment by Sayrix** [comment]
Move to Biome, that's what I did and it's faster and has better support
