### ISSUE TITLE
@typescript-eslint/parser@^5.0.1 does not exist

### ISSUE THREAD

**Issue by kenmckaba** [idahogurl/vs-code-prettier-eslint#238]
Setting up a new typescript project in vscode, error is output: "@typescript-eslint/parser@npm:5.0.1: No candidates found"
Note: that version of @typescript/eslint/parser does not exist in npmjs.org

**To Reproduce**
1) install the vs-code-prettier-eslint extension
2) follow the extension instructions
3) it says to run the following:
"yarn add -D prettier@^3.1.0 eslint@^8.52.0 prettier-eslint@^16.1.2 @typescript-eslint/parser@^5.0.1 typescript@^4.4.4"
4) error is output: "@typescript-eslint/parser@npm:5.0.1: No candidates found"

**Expected behavior**
It should install all required packages and work GREAT

**Example Project**
Execute specified yarn command on any project.
"yarn add -D prettier@^3.1.0 eslint@^8.52.0 prettier-eslint@^16.1.2 @typescript-eslint/parser@^5.0.1 typescript@^4.4.4"
or, more simply: "yarn add -D @typescript-eslint/parser@^5.0.1"

**Screenshots**
![image](https://github.com/user-attachments/assets/96a096c7-7357-420f-a5a9-9f793a7c5e75)

**Versions (please complete the following information):**
- VS Code Prettier ESLint extension: (I don't see any version) Last updated 2024-08-21, 11:58:56
- Visual Studio Code: 1.92.2
- Node: 20.17.0
- Package Manager: Yarn 4.4.1-git.20240825.hash-b2f315f6; npm 10.8.2
- prettier: 3.1.0
- eslint: 8.52.0

**System Specifications (please complete the following information):**
- OS: windows 11
- Processor: Intel i7
- RAM Size: 16 GB
 
**Additional context**

**Comment by kenmckaba** [comment]
I got it working by getting package values from an old working project which uses different versions of eslint and @typescript-eslint/parser than specified in the extension's doc:
yarn add -D prettier@^3.1.0 eslint@^8.56.0 prettier-eslint@^16.1.2 @typescript-eslint/parser@^7.2.0 typescript@^4.4.4

**Comment by kenmckaba** [comment]
Your example typescript app uses @typescript-eslint/parser@^5.1.0.  However prettier still does not run using that.
```["ERROR" - 9:45:51 PM] Error handling text editor change
["ERROR" - 9:45:51 PM] Invalid version
Error: Invalid version
    at t.isAboveV3 (c:\Users\ken\.vscode\extensions\esbenp.prettier-vscode-11.0.0\dist\extension.js:1:25515)
    at t.default.getSelectors (c:\Users\ken\.vscode\extensions\esbenp.prettier-vscode-11.0.0\dist\extension.js:1:11796)
    at t.default.handleActiveTextEditorChanged (c:\Users\ken\.vscode\extensions\esbenp.prettier-vscode-11.0.0\dist\extension.js:1:11123)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)```
