### ISSUE TITLE
Error: Failed to load plugin 'promise' declared in 'CLIOptions': The argument 'filename' must be a file URL object, file URL string, or absolute path string.

### ISSUE THREAD

**Issue by IntoLighter** [idahogurl/vs-code-prettier-eslint#45]
**Describe the bug**
My example project consists of root folder with script, package.json and eslint configuration and subfolder with react dummy project. When I run format one of the scripts in React's source `app/src` folder, I get an error:
```
Error: Failed to load plugin 'promise' declared in 'CLIOptions': The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received '' 
TypeError: Failed to load plugin 'promise' declared in 'CLIOptions': The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received ''
    at new NodeError (node:internal/errors:371:5)
    at createRequire (node:internal/modules/cjs/loader:1277:13)
    at Object.resolve (/Users/a/RiderProjects/Test/app/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:23:16)
    at Object.ModuleResolver.resolve (/Users/a/RiderProjects/Test/app/node_modules/@rushstack/eslint-patch/src/modern-module-resolution.ts:227:34)
    at ConfigArrayFactory._loadPlugin (/Users/a/RiderProjects/Test/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1051:33)
    at ConfigArrayFactory._loadPlugin (/Users/a/RiderProjects/Test/app/node_modules/@rushstack/eslint-patch/src/modern-module-resolution.ts:229:35)
    at /Users/a/RiderProjects/Test/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:942:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (/Users/a/RiderProjects/Test/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:938:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/a/RiderProjects/Test/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:738:44)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/a/RiderProjects/Test/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:678:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.create (/Users/a/RiderProjects/Test/app/node_modules/@eslint/eslintrc/lib/config-array-factory.js:473:16)
    at createCLIConfigArray (/Users/a/RiderProjects/Test/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:168:47)
    at CascadingConfigArrayFactory.clearCache (/Users/a/RiderProjects/Test/app/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:340:32)
    at new ESLint (/Users/a/RiderProjects/Test/app/node_modules/eslint/lib/eslint/eslint.js:448:32)
    at Pge (/Users/a/.vscode/extensions/rvest.vs-code-prettier-eslint-5.0.3/dist/extension.js:180:69)
    at /Users/a/.vscode/extensions/rvest.vs-code-prettier-eslint-5.0.3/dist/extension.js:188:700
    at Lge (/Users/a/.vscode/extensions/rvest.vs-code-prettier-eslint-5.0.3/dist/extension.js:180:1439)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**
Run format in one of scripts in React's source `app/src` folder.

**Expected behavior**
Fix errors by `eslint --fix`.

**Example Project**
https://github.com/IntoLighter/Prettier-eslint-bug

**Versions (please complete the following information):**
- VS Code Prettier ESLint extension: 5.0.3
- Visual Studio Code: 1.68.1
- Node: 18.4.0
- Package Manager: npm 8.13.1
- prettier: 2.7.1
- eslint: 8.3.0

**System Specifications (please complete the following information):**
- OS: MacOS Monterey 12.4
- Processor: Apple M1
- RAM Size: 16 GB

**Comment by mattbrannon** [comment]
@IntoLighter Try updating your version of eslint. The extension specifies `eslint@^8.7.0`

**Comment by IntoLighter** [comment]
Updating eslint in `app/node_modules` as pointed by @mattbrannon have solved the issue.

**Comment by maisoncastro** [comment]
I have the same problem, but I have `"eslint": "^8.9.0"`. What could I do?
